### ISSUE TITLE
[BUG] centos 7.6 下无法运行

### ISSUE THREAD

**Issue by hjue** [opensumi/core#1260]
centos 7.6 下无法运行

安装文档运行至步骤 `npm run start`，出现如下错误

```
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 3.10.0-1160.59.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/ide/sumi/core/node_modules/keytar
gyp ERR! node -v v14.19.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

OS: centos 7.6
node.js : v14.19.3
OpenSumi: git commit 9ba14d394928e639ec230ff6d7ba63f3dccbfb1e

**Comment by erha19** [comment]
@hjue 这个是由于你的容器环境内缺少 libsecret-1，可以手动安装一下，也可以写到 dockerfile 里面
