### ISSUE TITLE
[BUG] ide-electron 控制台出错

### ISSUE THREAD

**Issue by hnhhzy** [opensumi/core#2383]
```
E:\MakeProject\HeapsPlus\PEditor>yarn start
yarn run v1.22.19
$ electron --inspect=9229 .

Debugger listening on ws://127.0.0.1:9229/7d464cc3-5ee8-491b-8aeb-512b06ca37b1
For help, see: https://nodejs.org/en/docs/inspector
processArgv [
  'E:\\MakeProject\\HeapsPlus\\PEditor\\node_modules\\electron\\dist\\electron.exe',
  '--inspect=9229',
  '.'
]
馃殌 ~ file: index.ts ~ line 17 ~ launchFromCommandLine ~ argv []
working directory E:\MakeProject\HeapsPlus\PEditor
workspace undefined
[node]listenPath \\.\pipe\sumi-ipc-electron-windowdwBluMcAlhi6mUweyItmP
[node]server listen on path \\.\pipe\sumi-ipc-electron-windowdwBluMcAlhi6mUweyItmP
ready
[node][extHost:error] [extHost:error] [Extension-Host] Failed opening file C:\Users\hnhhzy\.sumi-oss\logs\20230308\extHost.log for writing: Permission denied

Error: Failed opening file C:\Users\hnhhzy\.sumi-oss\logs\20230308\extHost.log for writing: Permission denied
    at createRotatingLogger (E:\MakeProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:34:9)
    at E:\MakeProject\HeapsPlus\PEditor\node_modules\spdlog\index.js:27:7
    at E:\MakeProject\HeapsPlus\PEditor\node_mo...[node]listenPath \\.\pipe\sumi-ipc-electron-windowmzeEhySCy8VbOzs7mlGU2
```

控制台会显示日志文件`C:\Users\hnhhzy\.sumi-oss\logs\20230308\extHost.log`没有权限，权限其实是没问题的。文件里面也有东西。但是被其他进程挂住了，无法写入，变成只读
![image](https://user-images.githubusercontent.com/215678/223611464-e2c6d380-9137-407d-a522-3d8a90d2f2aa.png)

**Comment by erha19** [comment]
另外，这里的 Windows 日志也不应该写入至用户目录下，更合理的方式应该写入至 `~/AppData/Roaming/{配置文件}` 下

**Comment by zhuzeyu22** [comment]
same error ，permission denied ，some log error

**Comment by yantze** [comment]
可能是多个进程访问导致的，晚点看看

**Comment by zhuzeyu22** [comment]
是日志模块报的错，意思就是插件里的日志应该改成不直接写日志而是和日志服务通信，统一用日志服务来写日志这样来避免写锁报错么？

**Comment by yantze** [comment]
> 是日志模块报的错，意思就是插件里的日志应该改成不直接写日志而是和日志服务通信，统一用日志服务来写日志这样来避免写锁报错么？

是的，今天提交一个 pr 修复一下

**Comment by zhuzeyu22** [comment]
> > 是日志模块报的错，意思就是插件里的日志应该改成不直接写日志而是和日志服务通信，统一用日志服务来写日志这样来避免写锁报错么？
> 
> 是的，今天提交一个 pr 修复一下

没有看到相关 pr，日常催更，log service 和 log client 看不懂是什么东西

**Comment by yantze** [comment]
可能有一定的复杂度，今天再看看

**Comment by yantze** [comment]
@hnhhzy https://github.com/opensumi/core/pull/2415 已修复
