### ISSUE TITLE
[BUG] 调试 重启 失效，控制台报错：Error processing restart: TypeError: Cannot destructure property 'arguments' of 'undefined'

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2565]
**描述你的问题（Describe the bug）**

调试重启无效

![image](https://user-images.githubusercontent.com/13082375/230819159-8a5709bf-3b77-4cd4-b2c4-577fc5e7f994.png)

**复现路径（To Reproduce）**
- 进入调试
- 断点暂停时 点击重试按钮
- 非预期表现：无反应，控制台报错

```
"Error processing restart: TypeError: Cannot destructure property 'arguments' of 'undefined' as it is undefined.Error: Cannot destructure property 'arguments' of 'undefined' as it is undefined.
	at /Users/xx/workspace/apaas/ide/extensions/ms-vscode.js-debug/src/extension.js:2:979535
	at t.default._onMessage (/Users/xx/workspace/apaas/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1078485)
	at /Users/xx/workspace/apaas/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1076928
	at i.fire (/Users/xx/workspace/apaas/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1009035)
	at Socket._handleData (/Users/xx/workspace/apaas/ide/extensions/ms-vscode.js-debug/src/extension.js:2:1084437)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
```

**预期表现（Expected behavior）**
 重启调试

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: 2.23.3-rc-1680530879.0、2.21.8
- JS-Debug 插件版本： 2022.8.1217 、 1.77.1

**Comment by erha19** [comment]
我来处理一下
