### ISSUE TITLE
[BUG] 升级到 2.24.2 后报错 Uncaught Error: Cannot find Provider of Symbol(CLIENT_APP_TOKEN)

### ISSUE THREAD

**Issue by geekeren** [opensumi/core#2724]
**描述你的问题（Describe the bug）**

![image](https://github.com/opensumi/core/assets/13082375/30555820-6c29-433a-9fb8-edf310c6664e)

```
error.js:45 Uncaught Error: Cannot find Provider of Symbol(CLIENT_APP_TOKEN)
    at Object.noProviderError (error.js:45:1)
    at __webpack_modules__../node_modules/@opensumi/di/dist/injector.js.Injector.parseDependencies (injector.js:296:1)
    at __webpack_modules__../node_modules/@opensumi/di/dist/injector.js.Injector.get (injector.js:199:1)
    at ClientApp.createBrowserModules (app.js:237:1)
    at new ClientApp (app.js:145:1)
    at renderApp (render-app.ts:75:15)
    at renderApp (index.tsx:142:30)
    at renderApp (App.tsx:166:26)
```
**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: [e.g. macOS 11.2 Apple M1/Windows10/Windows11]
- Browser: [e.g. chrome, safari, electron]
- OpenSumi Version: [e.g. 2.13.0]

**Comment by bytemain** [comment]
检查下是不是有两份不同版本的 `@opensumi/di`，

**Comment by geekeren** [comment]
@bytemain 没有额
![Uploading image.png…]()

**Comment by bytemain** [comment]
可以参考下这个 issue：
- https://github.com/opensumi/core/issues/2411

排查后就是有多份 @opensumi/di

**Comment by bytemain** [comment]
如果你用的 pnpm，检查下 pnpm lock 里是不是有多个不同版本的 opensumi/xxx 包

**Comment by geekeren** [comment]
删除所有 node_module (包括 monorepo 的子目录中的node_module)后解决
