### ISSUE TITLE
[BUG] Docker 环境下 nsfw 引入失败

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#2976]
**描述你的问题（Describe the bug）**
Docker 环境下启动 ide-startup 项目，server 端报如下错误：
```
TypeError: n is not a function
    at n.start (/release/dist-node/index.js:329:4342)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async n.watchFileChanges (/release/dist-node/index.js:329:3025)
    at async v.watch (/release/dist-node/index.js:312:165419)
    at async t.RPCProxy.onRequest (/release/dist-node/index.js:41:88788)
```
经过排查发现是 nsfw 没有正确引入，`require('nsfw')` 返回空对象。

通过如下修改可以修复这个问题：
1. 使用相对路径引入 nsfw。
``` js
require('../../../../nsfw/js/src/index')
```
2. webpack.node.config.js 中对 .node 后缀的文件添加 node-loader
``` json
{
  test: /\.node$/,
  loader: require.resolve('node-loader'),
}
```
所以应该是 webpack 配置问题，希望用优雅的方式解决一下。

相关 issue：https://github.com/opensumi/core/issues/2950

**复现路径（To Reproduce）**
1. 在 Ubuntu 22.04 的容器中启动 Opensumi server，本地启动 Opensumi clinet，
4. 前端渲染完成后可以看到后端报错

**预期表现（Expected behavior）**
在 Docker 环境下能正确引入 nsfw

**环境信息（Environment）**
OS: Ubuntu 22.04.2 LTS Docker image
Browser: Chrome
Opensumi Version: 2.23.2

**Comment by sleepyyj** [comment]
@erha19

**Comment by erha19** [comment]
@sleepyyj 定位到问题了，确实是 webpack 配置写法的问题。
