### ISSUE TITLE
[Question] web端安装依赖启动项目报错

### ISSUE THREAD

**Issue by resetsix** [opensumi/core#3074]
下面是Vscode控制台依赖报错日志
# This file contains the result of Yarn building a package (electron@npm:22.3.24)
# Script name: postinstall

ReadError: The server aborted pending request
    at IncomingMessage.<anonymous> (C:\Users\Admin\Desktop\OpenSumi\node_modules\@electron\get\node_modules\got\dist\source\core\index.js:809:31)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.origin.emit (C:\Users\Admin\Desktop\OpenSumi\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketCloseListener (_http_client.js:389:11)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
    at TCP.done (_tls_wrap.js:568:7)
    
## 截图如下
![Snipaste_2023-09-19_18-11-37](https://github.com/opensumi/core/assets/85431995/52774278-6d64-45cb-b256-6a585fdb4e86)

# 环境配置
- win10
- node版本13.14.0
- python版本 3.10
- 有全局安装node-gyp （在OpenSumi目录下指定了set npm_config_python=E:\python.exe）
- 镜像使用的淘宝镜像

**Comment by AhkunTa** [comment]
可以尝试切到 2.26 分支 重新试下 main 分支下的的 electron 版本需要从从 github 下载部分依赖 导致超时

**Comment by resetsix** [comment]
> 可以尝试切到 2.26 分支 重新试下 main 分支下的的 electron 版本需要从从 github 下载部分依赖 导致超时

你好谢谢答复。我去试了下2.26版本，下载依赖后编译了25分钟终于编译完了，然后start的时候出现这个问题，是因为依赖没有下载完全吗？

![图片](https://github.com/opensumi/core/assets/85431995/97556a01-f317-4b29-9663-22211430cb23)

**Comment by AhkunTa** [comment]
看样子似乎初始化编译有问题 run init 过程没报错吗

**Comment by resetsix** [comment]
> 看样子似乎初始化编译有问题 run init 过程没报错吗

又拉了一遍代码重新安装依赖，编译了四十分钟，编译没有问题了。然后执行`yarn run init` 提示依赖包都报错了好奇怪呀
![图片](https://github.com/opensumi/core/assets/85431995/8e4ae971-6c2c-46f3-99a7-7b56d4dd5ef8)

**Comment by erha19** [comment]
@resetsix 你这里在安装依赖过程中应该还是有报错问题，找一下日志中的 Error 解决一下

**Comment by resetsix** [comment]
> @resetsix 你这里在安装依赖过程中应该还是有报错问题，找一下日志中的 Error 解决一下

好的 感谢大佬
