### ISSUE TITLE
[BUG] Windows docker 环境下 terminal 启动失败

### ISSUE THREAD

**Issue by sleepyyj** [opensumi/core#3326]
**描述你的问题（Describe the bug）**
使用 mcr.microsoft.com/windows/nanoserver 镜像作为后端的环境，使用 ide-startup 的前端连接，启动之后发现 terminal 无法正常使用。

Error log
```
[node:error] IPty#spawn native exception Error: Error launching WinPTY agent: agent died
    at new WindowsPtyAgent (C:\release\node_modules\node-pty\lib\windowsPtyAgent.js:77:36)
    at new WindowsTerminal (C:\release\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\release\node_modules\node-pty\lib\index.js:28:12)
    at v.$spawn (C:\release\dist-node\index.js:329:202641)
    at u.spawn (C:\release\dist-node\index.js:35:198779)
    at h.setupPtyProcess (C:\release\dist-node\index.js:169:130756)
    at h.start (C:\release\dist-node\index.js:169:130439)
    at async n.create2 (C:\release\dist-node\index.js:329:209401)
    at async p.create2 (C:\release\dist-node\index.js:329:211953)
    at async t.RPCProxy.onRequest (C:\release\dist-node\index.js:41:88988)
[node:error] Terminal process CLIENT_ID_HOEt2KS13VngIaSXbLUfy|uK0kTwKw9d2aYs4T479f8 start error
 {"message":"A native exception occurred during launch (Error launching WinPTY agent: agent died)"}
[node:error] CLIENT_ID_HOEt2KS13VngIaSXbLUfy|uK0kTwKw9d2aYs4T479f8 create terminal error: {"message":"A native exception occurred during launch (Error launching WinPTY agent: agent died)"}, options: {"executable":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe","args":[],"env":{}}
```
**复现路径（To Reproduce）**
Dockerfile
```
# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019 as builder

WORKDIR C:/Chocolatey
ENV chocolateyVersion=1.4.0

ADD https://chocolatey.org/install.ps1 install.ps1
RUN powershell -ExecutionPolicy Bypass -Command "iex .\install.ps1"

RUN choco --version
RUN choco install -y nodejs --version=16.14.0
RUN choco install -y python311
RUN choco install vscode -y

SHELL ["cmd", "/S", "/C"]
COPY ./docker/gcl/Install.cmd C:\TEMP\
ADD https://aka.ms/vscollect.exe C:\TEMP\collect.exe
ARG CHANNEL_URL=https://aka.ms/vs/17/release/channel
ADD ${CHANNEL_URL} C:\TEMP\VisualStudio.chman

RUN `
    curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe `
    `
    && (call C:\TEMP\Install.cmd vs_buildtools.exe --quiet --wait --norestart --nocache install `
        --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" `
        --channelUri C:\TEMP\VisualStudio.chman `
        --installChannelUri C:\TEMP\VisualStudio.chman `
        --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools `
        --add Microsoft.VisualStudio.Workload.VCTools `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
        --add Microsoft.VisualStudio.Component.Windows11SDK.22621 `
        --add Microsoft.VisualStudio.Component.VC.CMake.Project `
        --add Microsoft.VisualStudio.Component.TestTools.BuildTools `
        --add Microsoft.VisualStudio.Component.VC.ASAN `
        --add Microsoft.VisualStudio.Component.Windows10SDK.18362 `
        --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
        --add Microsoft.VisualStudio.Component.Windows10SDK.20348) `
    `
    && del /q vs_buildtools.exe

ENV VCINSTALLDIR "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC"

WORKDIR c:\\project

ARG SETX=/M
USER ContainerAdministrator
RUN setx %SETX% PATH "%PATH%;C:\Program Files\nodejs;C:\Users\ContainerAdministrator\AppData\Roaming\npm;"

WORKDIR c:\\project
COPY . .
RUN npm config set registry https://registry.npmmirror.com &&`
    npm install -g yarn &&`
    setx %SETX% PATH "%PATH%;C:\Users\ContainerAdministrator\AppData\Roaming\npm;" &&`
    yarn config set registry https://registry.npmmirror.com &&`
    npm config set python C:\python311\python.exe &&`
    npm config set msvs_version 2022 --global

FROM mcr.microsoft.com/windows/nanoserver:ltsc2019 as app

ENV EXTENSION_DIR %userprofile%\.sumi\extensions
ENV WORKSPACE_DIR c:\project\workspace
ENV EXT_MODE js
ENV HOMEPATH=C:\Users\ContainerAdministrator

RUN mkdir "%userprofile%\.sumi\extensions"
RUN mkdir "c:\project\workspace"

COPY --from=builder ["C:\\Program Files\\nodejs", "C:\\Program Files\\nodejs"]
COPY --from=builder  ["C:\\Windows\\System32\\WindowsPowerShell","C:\\Windows\\System32\\WindowsPowerShell"]

ENV VCINSTALLDIR "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC"

WORKDIR /release
ARG SETX=/M
USER ContainerAdministrator
RUN setx %SETX% PATH "%PATH%;C:\Program Files\nodejs;C:\Users\ContainerAdministrator\AppData\Roaming\npm;"

COPY ./dist dist
COPY ./dist-node dist-node
COPY ./hosted hosted
COPY ./node_modules_prod node_modules

CMD ["cmd"]
EXPOSE 8000
```

**预期表现（Expected behavior）**
terminal 可以正常使用

**环境信息（Environment）**

- OS: mcr.microsoft.com/windows/nanoserver:ltsc2019
- Browser: chrome
- OpenSumi Version: 2.27.0

**Comment by erha19** [comment]
@sleepyyj  不建议在 Windows 下部署.. 这块我暂时没能力验证程序健壮性，初步看是 pty 进程没有找到合适的 terminal 程序启动。

**Comment by sleepyyj** [comment]
@erha19 我做了一些 Windows 下的尝试，异常挺多的，这条路看来走不通。
