### ISSUE TITLE
[Question] 环境安装问题

### ISSUE THREAD

**Issue by goolin163** [opensumi/core#3518]
**我有在win10 win11安装环境，查看opensumi文档和vs code文档都不大顺利， 在core这个项目运行yarn命令出现一些错误。经过搜索解决多个错误后能正常运行 ，但测试ide-startup这个项目，运行yarn命令出现下面错误。后使用Mac os安装，安装过程比较顺利，core这个项目也正常运行，但ide-startup也是出现下面错误。 是否有个在一步步安装对应软件版本的流程。确保这些软件组合能正常运行项目**

**Comment by goolin163** [comment]
$ yarn
yarn install v1.22.22
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm run compile:worker-host && npm run compile:ext-host && npm run download:extensions

> startup@1.0.0 compile:worker-host
> cross-env NODE_ENV=production webpack --config ./configs/webpack.worker-host.config.js

/Users/apple/opensumi/ide-startup/node_modules/loader-runner/lib/LoaderRunner.js:106
			throw new Error("callback(): The callback was already called.");
			      ^

Error: callback(): The callback was already called.
    at context.callback (/Users/apple/opensumi/ide-startup/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at Object.ESBuildLoader (/Users/apple/opensumi/ide-startup/node_modules/esbuild-loader/dist/loader.js:62:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.1
error Command failed with exit code 1.
