### ISSUE TITLE
[BUG] explorer - workspace 文件操作表现异常

### ISSUE THREAD

**Issue by nxps** [opensumi/core#4051]
**描述你的问题（Describe the bug）**

1. workspace 目录下为空时，新建目录比如 `a`, 页面并不显示，即使点击上面的刷新按钮也是如此，只能刷新页面，才会显示

![image](https://github.com/user-attachments/assets/28a086ef-0f69-4611-bc64-a9e5f121a538)

![image](https://github.com/user-attachments/assets/64fdd6f8-77dc-40d1-aa34-23d4e3460476)

2. `a` 目录下有嵌套目录，直接删除顶层 `a`，并不生效

![image](https://github.com/user-attachments/assets/58ff72cc-a418-4547-8639-7fb155db7d38)

3. 批量删除文件，删除成功后，过几秒报错，另外删除有嵌套文件夹的显示也有问题，刷新后显示正常

![image](https://github.com/user-attachments/assets/8cac5aac-43b7-4067-aa10-4350e7af1f03)

![image](https://github.com/user-attachments/assets/340dfad1-5bfa-47bc-badf-9a644c27f6fc)

```
Uncaught Error: Cannot read properties of null (reading 'uri')

TypeError: Cannot read properties of null (reading 'uri')
    at MergeConflictContribution.getCacheResolvedConflicts (index.ts:443:35)
    at MergeConflictContribution.updateAllWidgets (index.ts:424:36)
    at UniqueContainer.value (index.ts:323:16)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:904:1)
    at UniqueContainer.value (codeEditorWidget.js:181:1)
    at Emitter._deliver (event.js:882:1)
    at Emitter.fire (event.js:912:1)
    at EditorConfiguration._recomputeOptions (editorConfiguration.js:72:1)
    at EditorConfiguration.updateOptions (editorConfiguration.js:120:1)
    at StandaloneEditor.updateOptions (codeEditorWidget.js:288:1)
    at StandaloneEditor.updateOptions (standaloneCodeEditor.js:223:1)
    at updateOptionsWithMonacoEditor (editor-collection.service.ts:233:16)
    at BrowserCodeEditor._doUpdateOptions (editor-collection.service.ts:339:5)
    at BrowserCodeEditor.updateOptions (editor-collection.service.ts:334:10)
    at CommentsService.updateEditorLayoutOptions (comments.service.ts:623:12)
    at CommentsService.<anonymous> (comments.service.ts:588:12)
    at Generator.next (<anonymous>)
    at tslib.es6.mjs:121:1
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.mjs:117:1)
    at CommentsService.tryUpdateReservedSpace (comments.service.ts:563:55)
    at UniqueContainer.value (comments.service.ts:512:14)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:917:1)
    at StandaloneEditor.setModel (codeEditorWidget.js:357:1)
    at UniqueContainer.value (codeEditorWidget.js:1242:1)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:917:1)
    at TextModel.dispose (textModel.js:257:1)
    at disposable.dispose (disposable.ts:207:7)
    at EditorDocumentModel.dispose (disposable.ts:164:33)
    at EditorDocumentModelServiceImpl._doDelete (editor-document-model-service.ts:147:11)
    at editor-document-model-service.ts:138:14
    at MergeConflictContribution.getCacheResolvedConflicts (index.ts:443:35)
    at MergeConflictContribution.updateAllWidgets (index.ts:424:36)
    at UniqueContainer.value (index.ts:323:16)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:904:1)
    at UniqueContainer.value (codeEditorWidget.js:181:1)
    at Emitter._deliver (event.js:882:1)
    at Emitter.fire (event.js:912:1)
    at EditorConfiguration._recomputeOptions (editorConfiguration.js:72:1)
    at EditorConfiguration.updateOptions (editorConfiguration.js:120:1)
    at StandaloneEditor.updateOptions (codeEditorWidget.js:288:1)
    at StandaloneEditor.updateOptions (standaloneCodeEditor.js:223:1)
    at updateOptionsWithMonacoEditor (editor-collection.service.ts:233:16)
    at BrowserCodeEditor._doUpdateOptions (editor-collection.service.ts:339:5)
    at BrowserCodeEditor.updateOptions (editor-collection.service.ts:334:10)
    at CommentsService.updateEditorLayoutOptions (comments.service.ts:623:12)
    at CommentsService.<anonymous> (comments.service.ts:588:12)
    at Generator.next (<anonymous>)
    at tslib.es6.mjs:121:1
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.mjs:117:1)
    at CommentsService.tryUpdateReservedSpace (comments.service.ts:563:55)
    at UniqueContainer.value (comments.service.ts:512:14)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:917:1)
    at StandaloneEditor.setModel (codeEditorWidget.js:357:1)
    at UniqueContainer.value (codeEditorWidget.js:1242:1)
    at Emitter._deliver (event.js:882:1)
    at Emitter._deliverQueue (event.js:893:1)
    at Emitter.fire (event.js:917:1)
    at TextModel.dispose (textModel.js:257:1)
    at disposable.dispose (disposable.ts:207:7)
    at EditorDocumentModel.dispose (disposable.ts:164:33)
    at EditorDocumentModelServiceImpl._doDelete (editor-document-model-service.ts:147:11)
    at editor-document-model-service.ts:138:14
    at errors.js:18:1
```

**复现路径（To Reproduce）**

如上

**预期表现（Expected behavior）**

**环境信息（Environment）**

- OS: macOS 14.6.1 Apple M1 Pro
- Browser: chrome
- OpenSumi Version: 3.4.0

**Comment by erha19** [comment]
@nxps 感谢反馈，已在 [v3.4.3](https://github.com/opensumi/core/releases/tag/v3.4.3) 版本修复
