### ISSUE TITLE
[BUG] 编译测试失败，无法开始。

### ISSUE THREAD

**Issue by houming818** [opensumi/core#562]
**描述你的问题（Describe the bug）**
按照README的说明，进行编译无法成功。

执行命令
```
$ npm install --canvas_binary_host_mirror=https://npmmirror.com/mirrors/canvas/
```
输出

```
npm ERR! code 1                                                                                                                                
npm ERR! path /data/workspace/src/opensumi_core/node_modules/canvas                                                                            
npm ERR! command failed                                                
npm ERR! command sh -c node-pre-gyp install --fallback-to-build                                                                                
npm ERR! Failed to execute '/home/stdhi/.nvm/versions/node/v16.14.0/bin/node /home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)          
npm ERR! node-pre-gyp info it worked if it ends with ok                                                                                        
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0                                                                                           
npm ERR! node-pre-gyp info using node@16.14.0 | linux | x64                                                                                    
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download                                                                       
npm ERR! node-pre-gyp info check checked for "/data/workspace/src/opensumi_core/node_modules/canvas/build/Release/canvas.node" (not found) 
npm ERR! node-pre-gyp http GET https://npmmirror.com/mirrors/canvas/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://npmmirror.com/mirrors/canvas/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://npmmirror.com/mirrors/canvas/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.14.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://npmmirror.com/mirrors/canvas/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/data/workspace/src/opensumi_core/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/stdhi/.cache/node-gyp/16.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/stdhi/.cache/node-gyp/16.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/stdhi/.cache/node-gyp/16.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/data/workspace/src/opensumi_core/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package pixman-1 was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `pixman-1.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'pixman-1' found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.11.0-46-generic
npm ERR! gyp ERR! command "/home/stdhi/.nvm/versions/node/v16.14.0/bin/node" "/home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release" "--napi_version=8" 
"--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /data/workspace/src/opensumi_core/node_modules/canvas
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/stdhi/.nvm/versions/node/v16.14.0/bin/node /home/stdhi/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/workspace/src/opensumi_core/node_modules/canvas/build/Release 
--napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/workspace/src/opensumi_core/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.11.0-46-generic
npm ERR! node-pre-gyp ERR! command "/home/stdhi/.nvm/versions/node/v16.14.0/bin/node" "/data/workspace/src/opensumi_core/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /data/workspace/src/opensumi_core/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stdhi/.npm/_logs/2022-03-07T06_52_35_901Z-debug-0.log
```

**复现路径（To Reproduce）**

**预期表现（Expected behavior）**

**问题截图（Screenshots）**

**环境信息（Environment）**

```
OS：  ubuntu-20.04
nvm:  v16.14.0
node: v16.14.0
代码版本： v2.15.3（d4297082a）
```

**补充信息（Additional context）**

**Comment by Aaaaash** [comment]
> npm ERR! No package 'pixman-1' found

主要是找不到这个包，尝试这个命令安装一下再试试
```
sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev -y
```

**Comment by houming818** [comment]
问题已解决。
