### ISSUE TITLE
[BUG] Cannot find module nsfw.node

### ISSUE THREAD

**Issue by ChesterBu** [opensumi/core#743]
**描述你的问题（Describe the bug）**

**复现路径（To Reproduce）**
ide-startup项目
yarn install  --ignore-scripts (因为内网环境安装@opensumi/vscode-vscode-ripgrep会下载不了)
yarn start

**预期表现（Expected behavior）**

项目可以启动

**问题截图（Screenshots）**
```js
40% building 235/254 modules 19 active /ide-startup/node_modules/lodash/lodash.jsError: Cannot find module '../../build/Release/nsfw.node'
Require stack:
- /ide-startup/node_modules/nsfw/js/src/index.js
- /ide-startup/node_modules/@opensumi/ide-file-service/lib/node/file-service-watcher.js
- /ide-startup/node_modules/@opensumi/ide-file-service/lib/node/disk-file-system.provider.js
- /ide-startup/node_modules/@opensumi/ide-file-service/lib/node/index.js
- /ide-startup/src/node/common-modules.ts
- /ide-startup/src/node/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._resolveFilename (/ide-startup/node_modules/tsconfig-paths/src/register.ts:90:36)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ide-startup/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
error Command failed with exit code 1.

```

**环境信息（Environment）**

- OS: centos7
- OpenSumi Version [e.g. 2.16.0]
**补充信息（Additional context）**

**Comment by erha19** [comment]
@ChesterBu 这个就是依赖安装问题，nsfw 依赖没安装上

**Comment by erha19** [comment]
duplicate #718
