### ISSUE TITLE
[TEST] 不合理的 test case 收集

### ISSUE THREAD

**Issue by bytemain** [opensumi/core#849]
我们有一些 CI 会莫名其妙的失败，这里做一下收集以供解决。

**Comment by bytemain** [comment]
packages/terminal-next/__tests__/node/terminal.service.client.test.ts

这个 case 跑不过了，但是当时手误设置了 only，所以一直没有触发

**Comment by bytemain** [comment]
```
FAIL packages/keymaps/__tests__/browser/keymaps.service.test.ts (7.731 s)
  ● KeymapsService should be work › 02 #API should be work › resetKeybinding method should be work

    expect(jest.fn()).toBeCalledTimes(expected)

    Expected number of calls: 5
    Received number of calls: 8

      234 |       };
      235 |       await keymapsService.resetKeybinding(keybinding);
    > 236 |       expect(mockKeybindingRegistry.registerKeybinding).toBeCalledTimes(5);
          |                                                         ^
      237 |     });
      238 |
      239 |     it('getWhen method should be work', () => {

      at Object.<anonymous> (packages/keymaps/__tests__/browser/keymaps.service.test.ts:236:57)


```

**Comment by dqhl76** [comment]
```
FAIL packages/core-common/__tests__/arrary.test.ts (11.082 s)
  ● Arrays › topAsync

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      239 |   });
      240 |
    > 241 |   test('topAsync', async () => {
          |   ^
      242 |     const cmp = (a: number, b: number) => {
      243 |       equal(typeof a, 'number');
      244 |       equal(typeof b, 'number');

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (packages/core-common/__tests__/arrary.test.ts:241:3)
```
这一条test case有时会超时，同一个代码，两次正常，超时了一次

**Comment by bytemain** [comment]
packages/remote-opener/__tests__/node/opener.service.test.ts

这个 test case 需要前后端通信，但目前没有模拟到通信

**Comment by bytemain** [comment]
在 github actions 的 macos 环境下出现了两次这个测试没过，其他环境都没有出现过：

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/13938334/167538774-b60f538c-1fcf-4d14-a2e6-0f0d9ae10b42.png">

![image](https://user-images.githubusercontent.com/13938334/167538844-d8a579e0-5ea3-4c2e-8e7a-d436d18d5fc0.png)

```

Summary of all failing tests
FAIL packages/terminal-next/__tests__/browser/client.test.ts (5.071 s)
  ● Terminal Client › Terminal Send Text

    expect(received).toBeGreaterThan(expected)

    Expected: > 0
    Received:   0

      118 |     const line = client.term.buffer.active.getLine(0);
      119 |     const lineText = (line && line.translateToString()) || '';
    > 120 |     expect(lineText.trim().length).toBeGreaterThan(0);
          |                                    ^
      121 |   });
      122 |
      123 |   it('Terminal Find Next', async () => {

      at Object.<anonymous> (packages/terminal-next/__tests__/browser/client.test.ts:120:36)
```
